# Generated by Django 5.0.2 on 2024-02-26 18:08

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_fname', models.CharField(max_length=200)),
                ('User_lname', models.CharField(max_length=100)),
                ('Phno', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('User_password', models.CharField(max_length=200)),
                ('User_repaeat_password', models.CharField(max_length=200)),
                ('User_email', models.EmailField(max_length=200)),
                ('User_adl', models.CharField(max_length=100)),
                ('User_adli', models.CharField(max_length=100)),
                ('User_adlin', models.CharField(max_length=100)),
            ],
        ),
    ]
